backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
media_folder: "site/static/img"
public_folder: "_site/static/img"
