name: compile

on:
  push:
    branches:
      - '**'
    paths:
      - '**.md'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    
    - name: Install Dependencies
      run: npx yarn install
      
    - name: Spellcheck
      run: npm run spellcheck